/**
 * @description: OOPS Concepts - Question-5:
 *               Override the abstract method created above.
 * @author: Sonali Kakade
 *
 * @revision:
 * Version      Date            Description
 * ------------------------------------------------
 * 1.0          10-May-2017     Initial revision.
 **/

public abstract class BaseClass {

    /**
     * @description: Abstract Method.
     * @author: Sonali Kakade
     * @date: 10-May-2017
     **/
    public abstract void display();
}