/**
 * @description: OOPS Concepts - Question-4:
 *               Implement an abstract method.
 * @author: Sonali Kakade
 *
 * @revision:
 * Version      Date            Description
 * ------------------------------------------------
 * 1.0          10-May-2017     Initial revision.
 **/

public class ImplementingClass implements InterfaceDemo {

    /**
     * @description: Sample method defination.
     * @author: Sonali Kakade
     * @date: 10-May-2017
     **/
    public void sampleMethod() {
        system.debug('In Derived Class.');
    }
}