/**
 * @description: OOPS Concepts - Question-4:
 *               Implement an abstract method.
 * @author: Sonali Kakade
 *
 * @revision:
 * Version      Date            Description
 * ------------------------------------------------
 * 1.0          10-May-2017     Initial revision.
 **/

public interface InterfaceDemo {

    /**
     * @description: Sample method declaration.
     * @author: Sonali Kakade
     * @date: 10-May-2017
     **/
    void sampleMethod();
}