/**
 * @description: OOPS Concepts - Question-1:
 *               Write a static method in a class and call it from another (nonstatic) class.
 * @author: Sonali Kakade
 *
 * @revision:
 * Version      Date            Description
 * ------------------------------------------------
 * 1.0          10-May-2017     Initial revision.
 * 1.1          14-Jun-2017     
 **/

public class StaticMethodClass {

    /**
     * @description: Static method to display.
     * @author: Sonali Kakade
     * @date: 10-May-2017
     **/
    public static void display() {
        System.debug('Static Method');
    }
}