/**************************************************************************************************
OOPS Concepts
Question-1:
Write a static method in a class and call it from another (nonstatic) class.
**************************************************************************************************/

public class CallStaticMethodClass {
    public void callStatic()
    {
    	StaticMethodClass.display();
    }
}