/**************************************************************************************************
OOPS Concepts
Question-4:
Implement an abstract method.
**************************************************************************************************/

public class ImplementingClass implements InterfaceDemo {
    public void sampleMethod() {
        system.debug('In Derived Class.');    
    }
}