/**************************************************************************************************
OOPS Concepts
Question-2:
Write a void method having non static declaration to debug/ print ‘Hello World’.
**************************************************************************************************/

public class PrintHelloWorld {
    public void display() {
    	System.debug('Hello World');
    }
}