/**
 * @description: OOPS Concepts - Question-2:
 *               Write a void method having non static declaration to debug/ print ‘Hello World’.
 * @author: Sonali Kakade
 *
 * @revision:
 * Version      Date            Description
 * ------------------------------------------------
 * 1.0          10-May-2017     Initial revision.
 **/

public class PrintHelloWorld {

    /**
     * @description: Non static method to print ‘Hello World’.
     * @author: Sonali Kakade
     * @date: 10-May-2017
     **/
    public void display() {
        System.debug('Hello World');
    }
}