/**************************************************************************************************
OOPS Concepts
Question-1:
Write a static method in a class and call it from another (nonstatic) class.
**************************************************************************************************/

public class StaticMethodClass {
    public static void display() {
    	System.debug('Static Method');
    }
}